# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'VM Connection'
    contents: '**test-program.py'
    targetFolder: '~/deploymentTest'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'VM Connection'
    runOptions: 'commands'
    commands: |
      sudo systemctl stop test-service
      sudo systemctl start test-service
    readyTimeout: '20000'

